services:
    ##### Library services


    deliveryman.config_manager.abstract:
        class: Deliveryman\Service\ConfigManager
        abstract: true
        public: false

    deliveryman.channel.abstract:
        class: Deliveryman\Channel\ChannelInterface
        abstract: true
        public: true
        autowire: true

    deliveryman.channel.http_graph.abstract:
        class: Deliveryman\Channel\HttpGraphChannel
        abstract: true
        public: true
        arguments:
            $configManager: '@deliveryman.config_manager.abstract'
        tags:
            - {name: 'deliveryman.channel', channel: 'http_graph'}

    deliveryman.validator.abstract:
        class: Deliveryman\Service\BatchRequestValidator
        abstract: true
        public: false
#        autowire: true
        arguments:
            $configManager: '@deliveryman.config_manager.abstract'

    deliveryman.normalizer:
        class: Deliveryman\Normalizer\BatchRequestNormalizer
#        autowire: true
        autoconfigure: true
        public: true
        tags: [serializer.normalizer]

    deliveryman.handler.abstract:
        class: Deliveryman\Service\BatchRequestHandlerInterface
        abstract: true

    deliveryman.handler.http_graph.abstract:
        class: Deliveryman\Service\BatchRequestHandler
        abstract: true
#        autowire: true
        arguments:
#            $channel: '@deliveryman.http_graph.abstract'
            $configManager: '@deliveryman.config_manager.abstract'
            $batchRequestValidator: '@deliveryman.validator.abstract'
        tags:
            - {name: 'deliveryman.handler', channel: 'http_graph'}

    deliveryman.channel_normalizer.abstract:
        class: Deliveryman\Normalizer\ChannelNormalizerInterface
        abstract: true

    deliveryman.channel_normalizer.http_graph:
        parent: deliveryman.channel_normalizer.abstract
        class: Deliveryman\Normalizer\HttpGraphChannelNormalizer
#        autowire: true
        arguments: ['@serializer']
        tags:
            - {name: 'deliveryman.channel_normalizer'}
